### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by amonetlol** [pemattern/fetchy#1]
I'm coming from reddit. As I saw that you mentioned that you had not tested it in other places besides your machine, I came to bring you feedback on how it is working on my machine.

alacritty:
![image](https://github.com/pemattern/fetchy/assets/65382640/64c16292-fbfe-4f6a-b2b4-7f76ba8b6ffc)

kitty:
![image](https://github.com/pemattern/fetchy/assets/65382640/812f845d-139e-4338-a3ae-ef2818ae2988)

OS: ok
Arch: ok
Kernel: ok
CPU: ok
Mem: ok (i guess)

**Comment by pemattern** [comment]
Thanks for the feedback! The GPU and Disk capacity are currently hard coded and not dynamic. Also Arch is the only ascii currently in place 😂

**Comment by pemattern** [comment]
Memory and Disk Capacity are implemented. GPU Info is implemented. Added Ascii Art for many Distros.
